name: flutter_bloc_architecture
description: "Paydash App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^14.6.2
  logging: ^1.3.0
  shared_preferences: ^2.3.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  retrofit: ^4.4.1
  dio: ^5.7.0
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
